CREATE TYPE tipo_funcionario AS ENUM ('GESTOR', 'VENDEDOR', 'ESTOQUISTA', 'ADMINISTRADOR');
CREATE TYPE unidade_item AS ENUM ('POTE', 'PACOTE', 'CAIXA', 'KG', 'LITRO', 'GRAMAS');

CREATE TABLE "Item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "unidade" unidade_item NOT NULL,
  "quantidade" int NOT NULL DEFAULT 0,
  "validade" date NOT NULL
);

CREATE TABLE "Produto" (
  "id_item" int PRIMARY KEY,
  "preco_venda" decimal(10,2) NOT NULL
);

CREATE TABLE "Insumo" (
  "id_item" int PRIMARY KEY,
  "fornecedor" varchar(100),
  "custo_referencia" decimal(10,2)
);

CREATE TABLE "Funcionario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "usuario" varchar(60) UNIQUE NOT NULL,
  "senha" varchar(255) NOT NULL,
  "tipo" tipo_funcionario NOT NULL,
  "ativo" bool NOT NULL DEFAULT true
);

CREATE TABLE "Cliente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "cnpj" varchar(14) UNIQUE NOT NULL,
  "email" varchar(150),
  "telefone" varchar(11),
  "criado_em" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "Venda" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" int NOT NULL,
  "id_vendedor" int NOT NULL,
  "valor_total" decimal(10,2) NOT NULL,
  "data" timestamp NOT NULL DEFAULT now(),
  "sincronizado" bool NOT NULL DEFAULT false
);

CREATE TABLE "Meta_Mensal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mes" smallint NOT NULL,
  "ano" smallint NOT NULL,
  "valor_meta" decimal(10,2) NOT NULL,
  "criado_por" int
);

CREATE TABLE "Venda_Produto" (
  "id_venda" int NOT NULL,
  "id_produto" int NOT NULL,
  "quantidade" int NOT NULL,
  "preco_unitario" decimal(10,2) NOT NULL,
  PRIMARY KEY ("id_venda", "id_produto")
);

ALTER TABLE "Produto" ADD FOREIGN KEY ("id_item") REFERENCES "Item" ("id");
ALTER TABLE "Insumo" ADD FOREIGN KEY ("id_item") REFERENCES "Item" ("id");
ALTER TABLE "Venda" ADD FOREIGN KEY ("id_cliente") REFERENCES "Cliente" ("id");
ALTER TABLE "Venda" ADD FOREIGN KEY ("id_vendedor") REFERENCES "Funcionario" ("id");
ALTER TABLE "Meta_Mensal" ADD FOREIGN KEY ("criado_por") REFERENCES "Funcionario" ("id");
ALTER TABLE "Venda_Produto" ADD FOREIGN KEY ("id_venda") REFERENCES "Venda" ("id");
ALTER TABLE "Venda_Produto" ADD FOREIGN KEY ("id_produto") REFERENCES "Produto" ("id_item");